name: Manhunt
version: '${project.version}'
main: me.tissub.manhunt.Main
api-version: 1.16
authors: [TissuB]
description: Manhunt plugin for minecraft 1.16+ created by TissuB
commands:
  manhunt:
    description: This command sets up the whole manhunt game
    usage: /<command>
permissions:
  manhunt.manhunt:
    description: Allows the player to use all /manhunt commands
    children:
      manhunt.add: true
      manhunt.remove: true
      manhunt.start: true
      manhunt.reset: true
      manhunt.list: true
      manhunt.help: true